CHANGES.rst
nengo_dl/tensor_graph.py
nengo_dl/tests/test_simulator.py

Better method for collecting optimizer variables

---

CHANGES.rst
nengo_dl/simulator.py

**Motivation and context:**
Be able to suppress the output from a simulation run, useful when running for little time repeatedly.
**Interactions with other PRs:**
none
**How has this been tested?**
not tested
**How long should this take to review?**
- Quick (less than 10 lines changed or changes are straightforward)
**Types of changes:**
- Add feature
**Checklist:**
- [n/a] I have updated the documentation accordingly.
- [n/a] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [n/a] I have run the test suite locally and all tests passed.

added progress_bar option to simulator.run

---

.travis.yml
CHANGES.rst
docs/examples/spa_memory.ipynb
docs/examples/spa_retrieval.ipynb
nengo_dl/benchmarks.py
nengo_dl/graph_optimizer.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_graph_optimizer.py
nengo_dl/tests/test_simulator.py

And some minor build efficiency/logging changes.

Use `tf.profiler` to collect profiling data

---

CHANGES.rst
nengo_dl/graph_optimizer.py
nengo_dl/op_builders.py
nengo_dl/signals.py
nengo_dl/tests/test_signals.py
nengo_dl/utils.py

Changed `TensorSignal` to store the minibatch size as part of this optimization.

Minor optimizations of reshape/identity/constant ops

---

CHANGES.rst
nengo_dl/neuron_builders.py
nengo_dl/tests/test_neurons.py

Improve numerical stability of LIFRate gradients

---

CHANGES.rst
nengo_dl/simulator.py
nengo_dl/tests/test_simulator.py
setup.py

Next release will be 0.6.0, since this is a potentially significant change in behaviour (although in practice I suspect no one would notice).

Reseed processes for each item in minibatch

---

CHANGES.rst
nengo_dl/simulator.py
nengo_dl/tests/test_simulator.py

Better error message for data < minibatch_size

---

.appveyor.yml
.codecov.yml
.travis.yml
CHANGES.rst
LICENSE.rst
docs/examples/spiking_mnist.ipynb
docs/simulator.rst
nengo_dl/benchmarks.py
nengo_dl/process_builders.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_nengo_tests.py
nengo_dl/tests/test_simulator.py
nengo_dl/tests/test_tensor_graph.py
setup.py

A grab-bag of small changes made while working on various projects.

Miscellaneous updates

---

CHANGES.rst
nengo_dl/tensor_graph.py
nengo_dl/tensor_node.py
nengo_dl/utils.py

More minor fixes that have come up as I'm working.

Miscellaneous updates 2

---

.travis.yml
CHANGES.rst
nengo_dl/__init__.py
nengo_dl/graph_optimizer.py
nengo_dl/learning_rule_builders.py
nengo_dl/neuron_builders.py
nengo_dl/op_builders.py
nengo_dl/process_builders.py
nengo_dl/signals.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tensor_node.py
nengo_dl/tests/test_neurons.py
nengo_dl/tests/test_signals.py
nengo_dl/tests/test_simulator.py
nengo_dl/tests/test_utils.py
nengo_dl/utils.py
requirements.txt
setup.py

Another grab-bag of small changes from recent work

Miscellaneous updates 3

---

.appveyor.yml
CHANGES.rst
nengo_dl/simulator.py

Handle non-op session errors

---

CHANGES.rst
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_simulator.py

Fixed node outputs changing after simulator is built

---

.ci/run_checks.bat
CHANGES.rst
LICENSE.rst
nengo_dl/tensor_graph.py
nengo_dl/tests/test_tensor_graph.py
setup.cfg
setup.py

Add support for boolean signals

---

.nengobones.yml
.templates/gpu.sh.template
.templates/remote-script.sh.template
.travis.yml
CHANGES.rst
docs/config.rst
docs/examples.rst
docs/examples/lmu.ipynb
docs/examples/spiking-mnist.ipynb
nengo_dl/benchmarks.py
nengo_dl/compat.py
nengo_dl/config.py
nengo_dl/op_builders.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_benchmarks.py
nengo_dl/tests/test_simulator.py
nengo_dl/tests/test_tensor_graph.py
nengo_dl/tests/test_tensor_node.py

Adds a simple LMU example, based on https://github.com/abr/neurips2019/blob/master/experiments/psMNIST-standard.ipynb.
Based on https://github.com/nengo/nengo-dl/pull/110, since that has some fixes needed here.
Right now this is using a quick monkeypatch to fix the issue identified in https://github.com/nengo/nengo/pull/1587.

Add LMU example

---

CHANGES.rst
nengo_dl/builder.py
nengo_dl/dists.py
nengo_dl/learning_rule_builders.py
nengo_dl/neuron_builders.py
nengo_dl/neurons.py
nengo_dl/op_builders.py
nengo_dl/process_builders.py
nengo_dl/simulator.py
nengo_dl/tensor_node.py
nengo_dl/tests/test_builder.py
nengo_dl/tests/test_simulator.py
nengo_dl/transform_builders.py
nengo_dl/utils.py

Testing this also revealed an issue with using the old-style `super` calls, so I went through and updated all of those while I was at it.

Use simulator progress bar as default for run progress bar

---

nengo_dl/simulator.py
nengo_dl/tests/test_keras.py

Applies the same data standardization/validation that we apply to training data to the validation data.

Handle validation_data in Simulator.fit

---

.travis.yml
CHANGES.rst
docs/examples/lmu.ipynb
docs/examples/spa-memory.ipynb
nengo_dl/callbacks.py
nengo_dl/compat.py
nengo_dl/config.py
nengo_dl/converter.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_keras.py
nengo_dl/tests/test_learning_rules.py
nengo_dl/tests/test_objectives.py
nengo_dl/tests/test_simulator.py
nengo_dl/tests/test_tensor_graph.py
nengo_dl/tests/test_tensor_node.py

A collection of minor bugfixes for data handling/validation.
Fixes #132 
Fixes #131 
Fixes #115 
Fixes #120 
Fixes #121

Data handling fixes

---

.nengobones.yml
.travis.yml
nengo_dl/tests/test_simulator.py

Ensures that we're loading the right event file in TF 2.2.
Also added slack notifications (based on https://github.com/nengo/nengo-bones/pull/97).

Fix bug in test_summaries

---

.templates/remote-script.sh.template

We switched to using Bones master in all projects, but I forgot to update this script.

Use Nengo Bones master in remote script

---

.templates/LICENSE.rst.template
LICENSE.rst

Standardized sphinx docs link with the rest of the Nengo repos.

Standardized sphinx docs link

---

.appveyor.yml
.nengobones.yml
.travis.yml
nengo_dl/tensor_graph.py
setup.py

And a minor fix for a SyntaxWarning introduced in Python 3.8.

Test against Python 3.8

---

.nengobones.yml
.pre-commit-config.yaml
nengo_dl/benchmarks.py
nengo_dl/converter.py
nengo_dl/learning_rule_builders.py
nengo_dl/simulator.py
nengo_dl/tensor_graph.py
nengo_dl/tests/test_converter.py
nengo_dl/tests/test_neurons.py
pyproject.toml
setup.py

Applies the new black release to the codebase.

Apply black 20.8b0

---

CHANGES.rst
nengo_dl/version.py

Current Nengo core development version is now 3.2.0.

Update Nengo development version

---

.nengobones.yml
CHANGES.rst
docs/examples/spa-memory.ipynb
docs/examples/spa-retrieval.ipynb
nengo_dl/compat.py
nengo_dl/converter.py
nengo_dl/tensor_graph.py
nengo_dl/tensor_node.py
nengo_dl/tests/test_converter.py

Adds support for TensorFlow 2.6, and some minor updates for changes in `pylint` and `keras-spiking`.

Add support for TensorFlow 2.6
