README.rst, docs/conf.py, docs/extra_objects.rst, docs/installation.rst, docs/resources.rst, docs/training.rst
See https://github.com/nengo/nengo/pull/1338 for details.
=> Point to new Nengo core doc location

CHANGES.rst, nengo_dl/graph_optimizer.py, nengo_dl/tests/test_tensor_graph.py
Fixes #9 
The problem was that we were ordering signals based on their label, so for networks containing objects with the same name (e.g., the two Nodes with label "square" in the Product network) that order was non-deterministic.
This changes it so that we sort signals based on their position in the op plan, which should be deterministic for a given Network.
=> Ensure signal ordering is deterministic

CHANGES.rst, docs/examples/pretrained_model.ipynb, nengo_dl/graph_optimizer.py, nengo_dl/learning_rule_builders.py
This fixes things on our end, but there is still an error because there are a lot of broken links in the `tensorflow/models` repo after the refactoring.  Should work once https://github.com/tensorflow/models/pull/2439 is merged.
=> Update link to tensorflow/models/research

CHANGES.rst, docs/conf.py, docs/simulator.rst, docs/training.rst, nengo_dl/benchmarks.py, nengo_dl/builder.py, nengo_dl/dists.py, nengo_dl/graph_optimizer.py, nengo_dl/neuron_builders.py, nengo_dl/process_builders.py, nengo_dl/signals.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tensor_node.py, nengo_dl/tests/test_simulator.py, nengo_dl/utils.py
Adds support for collecting data from the model during ``sim.train``, using the ``summaries`` argument.  See the updated documentation (``training.rst``) for usage details.
=> Output summary data during training

CHANGES.rst, nengo_dl/simulator.py, nengo_dl/tests/test_simulator.py
This reworks the parameter fetching logic so that all the requested parameters are fetched in a single `sess.run` call, rather than being fetched one at a time.  This can be a significant improvement when fetching large numbers of parameters (e.g., when using `sim.freeze_params`).
There are also two bugs that were discovered/fixed during this process:
1. When optimizing encoders in NengoDL we are effectively optimizing gains and encoders at the same time (because those are rolled together into the `scaled_encoders` parameter).  However, direct neural connections bypass those encoders, meaning that they are using the original, untrained gains. So when we use `get_nengo_params` we don't want to return the trained Ensemble gains (which we were doing previously), because that will change the …
=> Improve efficiency of parameter fetching

CHANGES.rst, nengo_dl/tensor_graph.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_tensor_node.py
1. Use ``tf.variable_scope(tf.get_variable_scope())`` instead of ``tf.variable_scope("")`` (see "Breaking Changes" in https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0).
2. Raise a warning when training a network with non-differentiable elements, rather than an error.  This fixes an error in `whitepaper2018_code.py` that I didn't notice until TF 1.9.0 was officially released (because that code isn't tested against pre-releases).  And, in hindsight, this is a better solution, since there may be legitimate cases where a user wants to call ``sim.train`` on a network that isn't (completely) differentiable.
=> TensorFlow 1.9.0 compatibility

CHANGES.rst, nengo_dl/benchmarks.py, nengo_dl/neuron_builders.py
This is a change that I also made in `nengo_extras` (see [here](https://github.com/nengo/nengo-extras/blob/cfc3bbc048112fe9a29bc4f6e50267aa243225ad/nengo_extras/keras.py#L44)).
Basically, for small `j`, `z = log(1 + exp(j/sigma))*sigma = sigma*exp(j/sigma)` since `log(1 + x) = x` for small `x`. Then, `log(1 + 1/z) = log((z + 1) / z) = log(1 / z)` since `z` is also small and `z + 1 = 1`. Finally, `log(1/z) = -log(z) = -log(sigma*exp(j/sigma)) = -j/sigma - log(sigma)`.
=> More accurate softlif in tensorflow

CHANGES.rst, nengo_dl/tensor_node.py, nengo_dl/tests/test_tensor_node.py
This adds better TensorNode validation at build time (previously the validation was only being done at network definition time, in the `size_out` validation).  Avoids the cryptic error message observed in #51.
=> Validate TensorNode output when size_out != None

.ci/run_checks.bat, CHANGES.rst, conftest.py, nengo_dl/__init__.py, nengo_dl/simulator.py, nengo_dl/tests/test_benchmarks.py, nengo_dl/tests/test_simulator.py
Synapses introduce a one-timestep delay, so it is almost certainly a mistake to be training a network for one timestep with non-`None` synapses.  This adds a warning to help users diagnose this issue (otherwise users just end up with poor training performance, which is hard to figure out).
Addresses #54
=> Add warning for 1-step training if synapse=None

.ci/run_checks.bat, CHANGES.rst, conftest.py, nengo_dl/__init__.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_benchmarks.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_tensor_graph.py
TensorSignal indices are loaded on-demand during the build process (since we may never need them, depending on how signals are merged).  This means that, depending on when a Signal is first accessed, the indices may be initialized inside or outside the Simulation while loop.  Normally that doesn't matter, unless we want to access that Signal through `tensor_graph.get_signal`.  That accesses the signal value statically, outside of the while loop, so the indices also need to be created outside the while loop.  This makes sure that is the case.
Fixes #56
=> Reload tf_indices outside while in get_tensor

.ci/run_checks.bat, LICENSE.rst, nengo_dl/tensor_graph.py, nengo_dl/tests/test_tensor_graph.py, setup.cfg, setup.py
Update some old links/typos, ensure decorated functions build properly, add `nengo` to `known-third-party`, and increase the minimum `sphinx_rtd_theme` version (for compatibility with sphinx 1.8.0).
Fixes #59
=> Update documentation build

CHANGES.rst, nengo_dl/tensor_node.py, nengo_dl/tests/test_tensor_node.py
The GUI checks the node's `output` attribute (even though that isn't used in NengoDL).  This change allows TensorNodes to pass that check, and then NengoDL can take over the simulation.
Note that sliders still won't work (this would require some changes to Nengo GUI, to allow it to insert values into TensorFlow).  But the value plots work, so you can see what's coming out of a TensorNode.
=> Allow TensorNode to run in Nengo GUI

.travis.yml, CHANGES.rst, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_simulator.py, setup.cfg
TensorFlow 1.11.0 (and most likely 1.12.0, as it is unlikely this will be fixed before then) has a bug that can cause the TensorFlow build process to enter an infinite loop (see https://github.com/tensorflow/tensorflow/issues/23383).  Unfortunately there is nothing we can do to fix this on the NengoDL side, we just have to avoid the situation that can trigger this bug.  A fix has been submitted on the TensorFlow side (see https://github.com/tensorflow/tensorflow/pull/23408), which hopefully will make it into the next release.
In the meantime, if you run into this in one of your models (this is most likely to manifest as a call to ``sim.train`` getting stuck at 0% progress), try downgrading to TensorFlow 1.10.0.
Also included an unrelated fix for a bug that could cause stochastic test …
=> Avoid TensorFlow 1.11.0 infinite loop bug

.appveyor.yml, .travis.yml, CHANGES.rst, docs/examples/spa_memory.ipynb, docs/examples/spa_retrieval.ipynb, docs/examples/spiking_mnist.ipynb, nengo_dl/signals.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_simulator.py
- Previously we were creating our own variable to track the training step; change this to use TensorFlow's [global_step](https://www.tensorflow.org/api_docs/python/tf/train/global_step) functionality
- Add option to disable progress bars in ``sim.train``/``sim.loss``, and fix a bug in ``sim.loss`` progress bar
=> Progress bar and global step changes

.ci/coverage.sh, .ci/docs.sh, .ci/test.sh, .travis.yml, CHANGES.rst, docs/_static/custom.css, docs/conf.py, nengo_dl/benchmarks.py, nengo_dl/tests/test_benchmarks.py
Also updates the benchmark to work with the latest version of the spaun code, and fixes a bug in the documentation building (PR builds were being treated like `master` builds).
=> Install spaun benchmark through pip

.templates/gpu.sh.template, .templates/setup.py.template, CHANGES.rst, setup.py
Adding a `pyproject.toml` switched us over into pep517-style pip installation, which means that `setup.py` gets executed within an isolated build environment. This makes it difficult to check whether or not `tensorflow` is installed, which breaks our conditional logic in `setup.py` which would attempt to look for a pre-existing `tensorflow-gpu` installation. This means that our `setup.py` was installing `tensorflow` overtop of an existing `tensorflow-gpu` installation, which breaks the GPU support.  
There are two fixes here. The first is a kind of hacky fix that attempts to find the original (non-isolated) `site-packages` directory and then look in there for `tensorflow-gpu`. It's hacky, but it preserves all the same functionality as before.
The second fix takes advantage of a change in …
=> Fix tensorflow-gpu installation check

.appveyor.yml, .nengobones.yml, .templates/LICENSE.rst.template, .travis.yml, CHANGES.rst, LICENSE.rst, conftest.py, docs/reference.rst, nengo_dl/__init__.py, nengo_dl/compat.py, nengo_dl/tensor_node.py, nengo_dl/tests/__init__.py, nengo_dl/tests/test_nengo_tests.py, nengo_dl/tests/test_processes.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_transforms.py, setup.cfg, setup.py
Removes dependence on Nengo's `conftest.py`, except for one remaining part where we're monkey-patching core's `Simulator` fixture.
Also disables autodoc on the `MessageBar` widget. The sphinx 2.2.0 release raises some mysterious error for the (minimal) docstrings in that object.  Looked into it briefly, but not clear why it's erroring (I suspect it's just a bug on sphinx's end). But it's not critical to have in the documentation since it isn't user facing, and will hopefully be replaced by the Keras progress bar system in the near future, so just disabled it to avoid the problem.
=> Switch to new pytest fixtures

.templates/docs/conf.py.template, CHANGES.rst, docs/conf.py, docs/examples/from-tensorflow.ipynb, nengo_dl/config.py, nengo_dl/simulator.py
The `training.html` page was removed in 3.0.  This updates the internal links, and adds a redirect for any external links.
=> Update links from former training.html page

CHANGES.rst, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_keras.py, nengo_dl/tests/test_simulator.py
By default, the Nengo DL simulator will use the learning phase as set by Keras (i.e. "test" mode for `predict/evaluate`, and "train" mode for `fit`).  However, sometimes it can be useful to be able to override Keras' default behaviour (e.g. if we want to use "train" mode in `predict`, so that we can check the output of a spiking model after its neurons are swapped to the rate equivalents).
This allows the learning phase to be overridden by setting the global Keras learning phase (using, e.g. `tf.keras.backend.set_learning_phase`) before the Simulator is constructed.
Also added an option to control the input values in `check_gradients` (for when we don't want to evaluate the gradients at zero).
=> Allow Simulator learning phase to be controlled by global Keras learning phase

CHANGES.rst, docs/citation.rst, docs/contributing.rst, docs/license.rst, docs/migration-guide.rst, docs/project.rst, docs/release-history.rst, nengo_dl/simulator.py, nengo_dl/tests/test_simulator.py
Also includes two minor renamings, which were prompted as I was writing the migration guide.
I also reorganized the `project` page to separate the different parts into their own documents, rather than one big long page (it was getting really long with all the changelog entries and migration guide).
=> Add migration guide

nengo_dl/simulator.py
The **kwargs should reference Keras' Model.fit instead of Model.evaluate.
=> Fix simulator.fit docstring to reference Model.fit

CHANGES.rst, nengo_dl/callbacks.py, nengo_dl/compat.py, nengo_dl/losses.py, nengo_dl/op_builders.py, nengo_dl/signals.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tensor_node.py, nengo_dl/tests/dummies.py, nengo_dl/tests/test_benchmarks.py, nengo_dl/tests/test_keras.py, nengo_dl/tests/test_signals.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_tensor_node.py, nengo_dl/utils.py, nengo_dl/version.py
Adds NengoDL support for the `transform=None` changes in Nengo core (https://github.com/nengo/nengo/pull/1591).
=> Support for transform=None

CHANGES.rst, nengo_dl/__init__.py, nengo_dl/converter.py, nengo_dl/neuron_builders.py, nengo_dl/neurons.py, nengo_dl/tests/test_converter.py, nengo_dl/tests/test_neurons.py
I went with the name `LeakyReLU`, because `SpikingLeakyRectifiedLinear` was just getting a bit too much I thought.
Based on #119 (since there are some general fixes there).
=> Add LeakyReLU neuron models

CHANGES.rst, docs/config.rst, docs/examples/spa-memory.ipynb, nengo_dl/benchmarks.py, nengo_dl/config.py, nengo_dl/graph_optimizer.py, nengo_dl/learning_rule_builders.py, nengo_dl/op_builders.py, nengo_dl/signals.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tensor_node.py, nengo_dl/tests/test_benchmarks.py, nengo_dl/tests/test_graph_optimizer.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_tensor_graph.py, nengo_dl/tests/test_tensor_node.py, nengo_dl/transform_builders.py
The main change here is avoiding storing simulator state for signals targeted by `set` operations (since that state will never be read).  
I also added some more graph simplification functions.  One (`remove_constant_copies`), I had previously disabled because it could change which signals are stored by `save_params`/`load_params`. But thinking about this more, that doesn't seem worth disabling it for. As long as the user is consistently using (or not using) `remove_constant_copies` in both networks, then save/load params will work fine. So better to have it enabled by default (users can still disable it if they run into problems).
The second one `remove_reset_incs`, I had previously completely removed because in general it seemed to make things worse. But I realized that this was largely …
=> More memory optimizations

.codecov.yml, .nengobones.yml, .templates/gpu.sh.template, .templates/remote-script.sh.template, CHANGES.rst, docs/tips.rst, nengo_dl/converter.py, nengo_dl/graph_optimizer.py, nengo_dl/simulator.py, nengo_dl/tests/test_converter.py, nengo_dl/tests/test_simulator.py
Also added some documentation on the tips and tricks page to address the issue of low firing rates.
=> Add firing rate scaling option to Converter

.travis.yml, CHANGES.rst, docs/examples/lmu.ipynb, docs/examples/spa-memory.ipynb, nengo_dl/compat.py, nengo_dl/config.py, nengo_dl/converter.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_keras.py, nengo_dl/tests/test_learning_rules.py, nengo_dl/tests/test_objectives.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_tensor_graph.py, nengo_dl/tests/test_tensor_node.py
This makes it easier to re-use saved weights between models, as models with different saved state variables can still use the same saved Keras parameters.
Fixes #133
=> Don't include saved state in keras_model.weights

CHANGES.rst, nengo_dl/converter.py, nengo_dl/tests/test_converter.py
Some improvements to get the Keras converter working with my network.
- Do not sort `source_tensor` list. This is no longer required, and is problematic for models that have an output that is used other places in the model (since the sorting puts all outputs at the end).
- ~~Use a single bias connection in `inference_only` mode. We don't need to worry about proper bias sharing since we're not training them. It's much faster to use one connection to do all the biases in this case.~~
TODO:
=> Converter improvements

CHANGES.rst, README.rst, docs/converter.rst, docs/examples.rst, docs/examples/keras-to-snn.ipynb, nengo_dl/converter.py, nengo_dl/simulator.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_benchmarks.py, nengo_dl/tests/test_converter.py
Have an initial draft up, looking for feedback. Right now it's a fair bit longer than other examples. 
- Where should I upload the pre-trained weights for the user to download and skip training themselves? (currently just ??? in the notebook)
- I'm not pumped on having `test_images_30` and `test_images_100`, but I didn't come up with a much better way to do generate and pass around two data that is presented for two different lengths of time. It'd be nice to make sure the user can run things out of order after the first few cells.
- I separated the plotting into 3 functions because it felt a bit cleaner, but could put them all back in the `run_network` function because they're not used anywhere else.
=> Keras -> SNN IPython notebook

CHANGES.rst, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/tests/test_converter.py
Two bugs being fixed here:
1. `shape_in` of the fallback activation TensorNode was being set incorrectly (should be `output_shape` not `input_shape`)
2. Biases were not being added to converted Dense layers with fallback activation functions.
=> Fix bug in converting Dense layers with fallback activation functions

.nengobones.yml, CHANGES.rst, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/graph_optimizer.py, nengo_dl/simulator.py, nengo_dl/tests/test_converter.py, nengo_dl/tests/test_graph_optimizer.py, nengo_dl/tests/test_learning_rules.py, nengo_dl/tests/test_nengo_tests.py, nengo_dl/tests/test_simulator.py, nengo_dl/tests/test_utils.py, nengo_dl/utils.py, setup.cfg
This functionality (and `Simulator.freeze_params`, which depends on it) had not been updated after the introduction of Sparse transforms.
Fixes #148
=> Support Sparse transforms in Simulator.get_nengo_params

CHANGES.rst, docs/examples/keras-to-snn.ipynb, nengo_dl/converter.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_simulator.py
Also added a bit more information to the Converter verification failure error message, and fixed a bug in the logging messages I discovered while looking at this.
=> Add notes on timeseries data to Keras example

.templates/LICENSE.rst.template, .templates/setup.py.template, CHANGES.rst, LICENSE.rst, docs/installation.rst, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/neuron_builders.py, nengo_dl/neurons.py, nengo_dl/tensor_graph.py, nengo_dl/tests/dummies.py, nengo_dl/tests/test_converter.py, nengo_dl/tests/test_graph_optimizer.py, nengo_dl/tests/test_neurons.py, nengo_dl/tests/test_simulator.py, setup.py
Adds support for the NeuronType changes introduced in https://github.com/nengo/nengo/pull/1609.
Also a few unrelated fixes to get tests passing after new releases in dependencies.
=> Support for recent neuron refactoring in Nengo core

CHANGES.rst, docs/converter.rst, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/tests/test_converter.py
Instead of building the whole model as a flattened list of layers in a single network, now we build each Keras model in its own Nengo Network, and the conversion process is scoped within each Network (rather than having general data structures stored in the Converter class). 
This avoids having to trace the Keras model to create a flat list of layers, which is problematic due to relying on some relatively fragile internal Keras implementation details (e.g., it was broken in TensorFlow 2.3). This should also just be a more robust approach overall, as it is much easier in Keras to extract the list of layers within a given Keras model, rather than having to figure out how all the models are connected to one another.
Note: based on #159, as there are some general fixes there
=> Convert nested Keras models recursively

CHANGES.rst, nengo_dl/tensor_graph.py, nengo_dl/tests/dummies.py
I don't think sliced signal probes have ever been working, but this omission was just revealed by the new tests in Nengo core.
=> Add support for sliced signal probes

CHANGES.rst, nengo_dl/converter.py, nengo_dl/tests/test_converter.py
Note: I can only find out what the warning message says by using pytest.warns with an incorrect match (-rw doesnt show anything)
This adds warning if a converter.swap_activations key is not used
This change allows transform distribution to work on freeze params
Quick (less than 40 lines changed or changes are straightforward)
Bug fix (non-breaking change which adds a warning)
- I have read the CONTRIBUTING.rst document.
- [na] I have updated the documentation accordingly.
- [na] I have included a changelog entry.
- I have added tests to cover my changes.
- I have run the test suite locally and all tests passed.
=> Add warning if key isnt used

CHANGES.rst, docs/examples/keras-to-snn.ipynb, nengo_dl/compat.py, nengo_dl/learning_rule_builders.py, nengo_dl/tensor_graph.py, nengo_dl/tests/test_tensor_graph.py
Raise an error if advanced indexing is used, and fix the same bug found in nengo core (when applying PES learning on a neuron-to-neuron connection with a post slice).
=> Update to support core SimPES changes

.nengobones.yml, CHANGES.rst, README.rst, docs/examples/from-tensorflow.ipynb, docs/resources.rst, nengo_dl/callbacks.py, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/losses.py, nengo_dl/neuron_builders.py, nengo_dl/tensor_node.py, nengo_dl/tests/dummies.py, nengo_dl/tests/test_builder.py, nengo_dl/tests/test_converter.py, setup.py
Also added support for TimeDistributed layers, since that's present in a lot of KerasSpiking models. And then added some pointers to KerasSpiking in various places throughout the documentation.
=> Add support for KerasSpiking layers

.nengobones.yml, docs/installation.rst, nengo_dl/tests/test_keras.py
TF 2.4 uses CUDA 11.0 and CUDNN 8.0, so we need to switch to installing those in the builds using TF 2.4.
=> Update CUDA versions for TF2.4

CHANGES.rst, nengo_dl/neuron_builders.py, nengo_dl/tests/test_neurons.py
If the neuron builder ``step`` function does not return the correct
number of states, raise a clear error. Previously, this would fail
on a cryptic error in TF < 2.4, or fail silently in TF >= 2.4.
Addresses #198.
=> Add error for neuron builder step return length

.nengobones.yml, CHANGES.rst, nengo_dl/converter.py, nengo_dl/tests/test_converter.py, setup.py
I don't think it's worth trying to be backwards compatible here, since it's an optional dependency.
=> Increase minimum keras-spiking version to 0.3

.nengobones.yml, .pre-commit-config.yaml, CHANGES.rst, nengo_dl/compat.py, nengo_dl/graph_optimizer.py, nengo_dl/tests/test_graph_optimizer.py, nengo_dl/tests/test_transforms.py, nengo_dl/transform_builders.py, setup.cfg
Support the ConvTransposeInc operator added in nengo/nengo#1648.
Things might be a bit cleaner if we support `GeneralConvInc` instead of `ConvInc` and `ConvTransposeInc` (then e.g. we could have one `GeneralConvSet` operator), but some code (e.g. operator merging) breaks if we don't have build methods for each operator class (if we try to do them only for a superclass).
TODO:
=> Convolution transpose

.github/workflows/ci.yml, .nengobones.yml, .templates/setup.py.template, CHANGES.rst, LICENSE.rst, docs/conf.py, docs/examples/spa-memory.ipynb, nengo_dl/compat.py, nengo_dl/simulator.py, nengo_dl/tests/test_simulator.py, nengo_dl/utils.py, nengo_dl/version.py, setup.cfg, setup.py
Based on https://github.com/nengo/nengo-dl/pull/228, with some minor fixups (updating the source `setup.py` template, and adding a changelog entry). Plus some unrelated commits to get tests passing again due to environmental changes (e.g. new `black` release).
=> Installation detects tensorflow-macos installation

.nengobones.yml, CHANGES.rst, nengo_dl/compat.py, nengo_dl/converter.py, nengo_dl/tests/test_converter.py
Motivation and context:
There is a (tentatively) accepted pull request for adding[ grouped convolutions to nengo](https://github.com/nengo/nengo/tree/convolution-groups-ci) already. Before adding grouped convolutions to nengo-loihi it is neccessary to add grouped convolutions to nengo-dl.
Related Forum Posts
https://forum.nengo.ai/t/adding-a-groups-parameter-for-convolutions-in-nengo-loihi/2035/2
https://forum.nengo.ai/t/trying-to-understand-nengo-transforms-convolution/1844/4?u=mjurado3
Interactions with other PRs:
This change is dependent upon this pull requrest in the nengo repository: https://github.com/nengo/nengo/pull/1684
How has this been tested?
This is tested through the test_conv in nengo_dl/tests/test_converter.py
How long should this take to review?
30 minutes if there are no …
=> Added groups param to convolutions
